[package]
name = "async_prometheus"
version = "0.1.0"
authors = ["Jacob Smith <jacob101607@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-rwlock = "1.3"
futures = "0.3"
memchr = "2.3"
